language: java
jdk:
  - oraclejdk8

before_script: true
script: mvn package

notifications:
  hipchat:
    rooms:
      - hioZ560EbacM9lhww5TXOn4josqxd4diCrwjPro6@Object-team
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    